# Generated by Django 4.0 on 2024-10-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happifyapp', '0002_activity_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
