# Generated by Django 4.0 on 2024-11-15 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happifyapp', '0004_preference_remove_userpreference_activities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_activity', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happifyapp.useraccount')),
            ],
        ),
    ]
